version: "3"
services:
  mysql_HigherOrLower:
    container_name: mysql_HigherOrLower
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: higherlower
      MYSQL_PASSWORD: HIGHERLOWER
      MYSQL_DATABASE: higherlower
      MYSQL_ROOT_PASSWORD: nlpacheco
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  higherlowergameapi:
    image: nlpacheco/higherlowergameapi
    build:
      context: .
      dockerfile: dockerfile.buildGame.yml
    container_name: higherlowergameapi
    depends_on:
      - mysql_HigherOrLower
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "5000:80"
