# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY HigherOrLowerAPI/*.csproj ./HigherOrLowerAPI/
COPY HigherOrLowerBusiness/*.csproj ./HigherOrLowerBusiness/
COPY TestProject.HigherOrLower/*.csproj ./TestProject.HigherOrLower/
RUN dotnet restore

# copy everything else and build app
COPY HigherOrLowerAPI/. ./HigherOrLowerAPI/
COPY HigherOrLowerBusiness/. ./HigherOrLowerBusiness/
COPY TestProject.HigherOrLower/. ./TestProject.HigherOrLower/
WORKDIR /source/HigherOrLowerAPI
RUN dotnet publish -c release -o /app 

# test stage -- exposes optional entrypoint
# target entrypoint with: docker build --target test
FROM build AS test
WORKDIR /source/tests
COPY TestProject.HigherOrLower/ .
ENTRYPOINT ["dotnet", "test", "--logger:trx"]

FROM build AS publish
RUN dotnet publish -c release --no-build -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "HigherOrLowerAPI.dll"]
